Repository antvis/L7Editor, pull requests merged in 2023-10, with the labels that each got.

#1 chore: 补充 Github 首页说明
  .github/workflows/lint.yml
  .github/workflows/preview.yml
  .github/workflows/release.yml
  package.json
  src/components/app-header/btn/download-btn.tsx
  src/components/app-header/btn/import-btn/file-upload.tsx
  src/components/app-header/btn/import-btn/index.tsx
  src/components/app-header/btn/import-btn/lnglat-import-btn.tsx
  src/components/app-header/btn/import-btn/url-upload.tsx
  src/components/app-header/index.tsx
  src/components/app-header/styles.ts
  src/components/app-map/index.tsx
  src/components/app-table/index.tsx
  src/components/geojson-editor/index.tsx
  src/components/layer-contextmenu-popup/code-block.tsx
  src/components/layer-contextmenu-popup/index.tsx
  src/components/layer-list/index.tsx
  src/components/layer-popup/index.tsx
  src/components/lnglat-editor/index.tsx
  src/components/map-content/index.tsx
  src/components/map-control-group/administrative-select-control/index.tsx
  src/components/map-control-group/draw-control/index.tsx
  src/components/map-control-group/filter-form-list-control/index.tsx
  src/components/map-control-group/filter-form-list-control/numberFilter.tsx
  src/components/map-control-group/filter-form-list-control/stringFilter.tsx
  src/components/map-control-group/filter-form-list-control/styles.ts
  src/components/map-control-group/index.tsx
  src/components/map-control-group/location-search-control/index.tsx
  src/components/map-control-group/official-layer-control/index.tsx
  src/components/map-control-group/official-layer-control/styles.ts
  src/components/map-control-group/sam-control/index.tsx
  src/components/map-control-group/save-map-options-control/index.tsx
  src/components/resize-panel/index.tsx
  src/components/resize-panel/styles.ts
  src/components/text-layer/index.tsx
  src/components/wkt-editor/index.tsx
  src/hooks/use-filter-features.ts
  src/locales/index.ts
  src/pages/components/editor.tsx
  src/pages/index.tsx
  src/recoil/atomState.ts
  src/recoil/feature.ts
  src/recoil/lnglat.ts
  src/types/filter.ts
  src/types/l7editor.ts
  src/utils/file-to-source.ts
  src/utils/gcoord.ts
  src/utils/index.ts
  src/utils/lnglat.ts
  src/utils/transform.ts
Labels: ignore-for-release

#2 docs: 1.补充官网 CNAME 2.订正官网打包路径
  .dumirc.ts
  .gitignore
  docs/CNAME
  package.json
Labels: documentation

#3 fix: 修复主题选择为非 light 时重复刷新页面切换为 light 问题
  src/pages/components/editor.tsx
Labels: bugfix

#4 fix: 补全中英互译字段
  src/components/app-table/index.tsx
  src/locales/langs/en-US.ts
  src/locales/langs/zh-CN.ts
  src/pages/components/editor.tsx
Labels: bugfix

#5 fix: 修复初始化页面两次触发bbox问题
  src/components/geojson-editor/index.tsx
Labels: bugfix

#6 docs: 更新 README.md 说明
  README.md
Labels: documentation

#7 fix: 将 IconFont 组件通过本地 js 实现替换接口请求方式
  package.json
  src/components/map-control-group/save-map-options-control/index.tsx
  src/constants/iconfont.js
  src/constants/iconfont.tsx
  src/constants/index.ts
  src/pages/index.tsx
Labels: bugfix

#9 fix: 将 IconFont 组件迁移至 components 内
  src/components/app-header/btn/i18n-btn.tsx
  src/components/app-header/index.tsx
  src/components/iconfont/index.tsx
  src/components/map-content/index.tsx
  src/components/map-control-group/administrative-select-control/index.tsx
  src/components/map-control-group/auto-control/index.tsx
  src/components/map-control-group/clear-control/index.tsx
  src/components/map-control-group/official-layer-control/index.tsx
  src/components/map-control-group/sam-control/index.tsx
  src/components/map-control-group/save-map-options-control/index.tsx
  src/constants/index.ts
Labels: bugfix

#10 docs: 替换 README 的 img 图片
  README.md
Labels: documentation

#11 chore: 升级版本号
  package.json
Labels: ignore-for-release

#12 fix: 设置修改为只有 baseMap 发生改变时触发刷新
  package.json
  src/components/app-header/btn/setting-btn.tsx
Labels: bugfix
