Repository antvis/L7Editor, pull requests merged in 2024-03, with the labels that each got.

#54 fix: 底图 customTiles 属性透出和文档补充
  docs/docs/index.md
  package.json
  src/components/map-control-group/official-layer-control/index.tsx
  src/locales/langs/zh-CN.ts
  src/pages/index.tsx
  src/recoil/atomState.ts
  src/types/l7editor.ts
Labels: bugfix

#53 feat: 完成获取地图参数组件
  src/components/map-control-group/index.tsx
  src/components/map-control-group/l7-option-control/index.tsx
  src/constants/iconfont.js
  src/locales/langs/en-US.ts
  src/locales/langs/zh-CN.ts
  src/types/l7editor.ts
Labels: feature

#55 docs: 修复 custom-tiles 跳转问题
  docs/docs/index.md
Labels: documentation

#47 fix: 修复 geojson 数据校验错误的问题
  package.json
  src/components/app-header/btn/import-btn/file-upload.tsx
  src/pages/components/editor.tsx
  src/recoil/feature.ts
Labels: bugfix

#52 feat: 新增导出图片组件
  .vscode/settings.json
  docs/docs/index.md
  src/components/map-control-group/export-image-control/index.tsx
  src/components/map-control-group/export-image-control/styles.ts
  src/components/map-control-group/index.tsx
  src/constants/index.ts
  src/locales/langs/en-US.ts
  src/locales/langs/zh-CN.ts
  src/types/l7editor.ts
  src/utils/index.ts
Labels: feature

#57 fix: 暂时关闭谷歌卫星地图和 SAM 地理识别控件
  src/components/map-control-group/index.tsx
  src/components/map-control-group/official-layer-control/index.tsx
Labels: bugfix

#59 feat: 去除 geojsonhint 依赖
  package.json
  src/pages/components/editor.tsx
  src/recoil/feature.ts
Labels: feature
